// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViuvOmhIHfBnAWjTrgATf5g63Imtpklg',
    appId: '1:95461439416:web:98ffc2fc4af1050f61814d',
    messagingSenderId: '95461439416',
    projectId: 'yashviflutterapp',
    authDomain: 'yashviflutterapp.firebaseapp.com',
    storageBucket: 'yashviflutterapp.firebasestorage.app',
    measurementId: 'G-T4R1N4P5P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0S2Zc0dE4nOGegbvdK6YO7j0vjxuURe4',
    appId: '1:95461439416:android:24fc16d3d51b31eb61814d',
    messagingSenderId: '95461439416',
    projectId: 'yashviflutterapp',
    storageBucket: 'yashviflutterapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJI6faL_DDg2Pmhfa8XD58CE1vZcCHDk',
    appId: '1:95461439416:ios:a410ccff8a61319661814d',
    messagingSenderId: '95461439416',
    projectId: 'yashviflutterapp',
    storageBucket: 'yashviflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.yashviFlutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJI6faL_DDg2Pmhfa8XD58CE1vZcCHDk',
    appId: '1:95461439416:ios:a410ccff8a61319661814d',
    messagingSenderId: '95461439416',
    projectId: 'yashviflutterapp',
    storageBucket: 'yashviflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.yashviFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAViuvOmhIHfBnAWjTrgATf5g63Imtpklg',
    appId: '1:95461439416:web:4596f87859c27c9661814d',
    messagingSenderId: '95461439416',
    projectId: 'yashviflutterapp',
    authDomain: 'yashviflutterapp.firebaseapp.com',
    storageBucket: 'yashviflutterapp.firebasestorage.app',
    measurementId: 'G-812M8JSME4',
  );
}
